#!/usr/bin/env bash

rm -rf autom4te.cache/ \
	configure \
	config.* \
	stamp-h1 \
	src/.deps \
	utils/.deps/ \
	src/Makefile \
	src/Makefile.in \
	utils/Makefile \
	utils/Makefile.in \
	Makefile \
	Makefile.in \
	src/*.o \
	src/piedock \
	utils/*.o \
	utils/piedockutils

automake && aclocal && autoconf

rm -rf autom4te.cache/
