#!/usr/bin/env bash

NAME=piedock
OBJECTS="AUTHORS \
	COPYING \
	ChangeLog \
	Doxyfile \
	INSTALL \
	Makefile.am \
	Makefile.in \
	NEWS \
	README \
	aclocal.m4 \
	configure \
	configure.ac \
	depcomp \
	install-sh \
	missing \
	mkinstalldirs \
	res \
	sh \
	src \
	utils"

[ -d sh ] || {
	echo "run this script from the project root"
	exit 1
}

[ -r src/main.cpp ] || {
	echo "cannot find src/main.cpp"
	exit 1
}

VERSION=`grep -oE "[0-9]\.[0-9]\.[0-9]" src/main.cpp`

sh/autogen

[ -d $NAME-$VERSION ] && {
	echo "$NAME-$VERSION already exists"
	exit 1
}

mkdir $NAME-$VERSION
cp -r $OBJECTS $NAME-$VERSION/
tar cjvf $NAME-$VERSION.tar.bz2 $NAME-$VERSION
rm -rf $NAME-$VERSION
