#!/bin/bash

# check if configure is available
[ -x configure ] || {
	echo "error: missing configure script"
	exit -1
}

[ -x sh/setup ] || {
	echo "error: missing setup script"
	exit -1
}

for (( RUNS=2; RUNS--; ))
do
	./configure && {
		# build, install, setup and run
		make && sudo make install && sh/setup && PieDock &&
			cat <<EOF

Congratulations! PieDock was successfully installed and run!

You may press one of the following combinations to make the menu
appear:

    Windows-key + left mouse button
    Windows-key + scroll wheel up
    Windows-key + scroll wheel down

To fine tune the experience, check out the configuration file:

$RC

EOF

		break
	}

	ERROR_STRING="error: libraries cannot be installed"

	# try to get libraries on Ubuntu or Debian
	which apt-get &>/dev/null && {
		sudo apt-get -y --no-upgrade install g++ \
			libx11-dev \
			libpng-dev \
			libxrender-dev \
			libxft2-dev \
			libfreetype6-dev || {
			echo ERROR_STRING
			exit -1
		}

		continue
	}

	# try to get libraries on openSUSE
	which zypper &>/dev/null && {
		sudo zypper --non-interactive install gcc-c++ \
			make \
			xorg-x11-libX11-devel \
			xorg-x11-libXrender-devel \
			libpng14-devel \
			freetype2-devel || {
			echo ERROR_STRING
			exit -1
		}

		continue
	}

	# try to get libraries on Fedora
	which yum &>/dev/null && {
		sudo yum install gcc-c++ \
			make \
			xorg-x11-libX11-devel \
			xorg-x11-libXrender-devel \
			libpng14-devel \
			freetype2-devel || {
			echo ERROR_STRING
			exit -1
		}

		continue
	}

	# build on Gentoo
	which emerge &>/dev/null && {
		# assuming X libraries are installed already
		sudo emerge --noreplace libpng \
			libXrender \
			libXft \
			freetype || {
			echo ERROR_STRING
			exit -1
		}

		continue
	}

	echo "error: sorry, your system's package management is not supported."
	exit -1
done
